language: generic
sudo: false

script:
  - emacs --version
  - make test

env:
  matrix:
    - EVM_EMACS=emacs-24.1-travis
    - EVM_EMACS=emacs-24.2-travis
    - EVM_EMACS=emacs-24.3-travis
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask

addons:
  apt:
    packages:
    - python-poppler

notifications:
  email: false
