#+TITLE:     PDF Tools README
#+AUTHOR:    Andreas Politz
#+EMAIL:     politza@fh-trier.de

** Prerequisites
   + GNU/Linux OS
   + convert 

     See http://www.imagemagick.org .
   + GNU Emacs 24 

     Preferably with imagemagick support.  
   + poppler-glib (>= 0.16)

     Some features require a more recent version.
     - >= 0.19.4 :: Creating and modifying text-annotations.
     - >= 0.22 :: Searching case-sensitive.
   + glib

     This is obviously a prerequisite for poppler-glib and the version
     should match it.
   + poppler-private
     
     This library contains some needed private poppler headers.
     Depending on the way poppler is installed on your system, this
     may or may not be included.  E.g. in Debian it is contained in a
     seperate package called libpoppler-private-dev.

** Building
  First run autogen.sh, then
#+begin_src sh
  ./configure && make
#+end_src
  which compiles the c source and creates a ELPA package.
** Installation
  Assuming the epdfinfo server build correctly and a Emacs package was
  created.  The next step is to install this package, with make
  via
#+begin_src sh
  make install-package
#+end_src
  or
#+begin_src sh
  make EMACS=/path/to/emacs install-package
#+end_src
  
  Alternatively from within Emacs via
#+begin_src elisp
  M-x package-install-file RET pdf-tools-${VERSION}.tar RET
#+end_src
  Finally put
#+begin_src elisp
  (pdf-tools-install)
#+end_src
  somewhere in your .emacs.  Try
#+begin_src elisp
  M-x pdf-tools-help RET
#+end_src
  for a overview of most features.

** Features
*** Render
    Display search results, links and annotations directly on the page,
    with customizable styles.
*** Isearch 
    Interactively search PDF documents like any other buffer, though
    there is currently no regexp support. 
*** Following links
    Click on highlighted links, moving to some part of a different
    page, some external file, a website or any other URI.  Links may
    also be followed by keyboard commands.
*** Annotations
    Display and list text-annotations, edit their contents and some
    attributes, move them around, delete them or create new ones and
    then save the modifications back to the PDF file.
*** Attachments
    Save files attached to the PDF-file or list them in a dired buffer.
*** Outline
    Use imenu or a special buffer to examine and navigate the PDF's
    outline.
*** SyncTeX
    Jump from a position on a page directly to the TeX source and
    vice-versa.
*** Misc
   + Display PDF's metadata.
   + Select and copy text from the PDF.
   + Search for occurences of a string.
   + Keep track of visited pages via a history.
   + Auto-fit pages to the current window size.
   + View multiple pages in multiple windows.

# Local Variables:
# mode: org
# End:
